### ISSUE TITLE
mongo db import failed

### ISSUE THREAD

**Issue by jannik8x8** [nilshartmann/react-vote-example#8]
I started reading the book and I tried to import the data into the mongo-db with the command "npm run import-mongodb-data". I have npm in version 3.10.10, nodejs v6.11.2 under ubuntu.
Mongo-db is: db version v2.6.10
The import failed with the following output:

connected to: 127.0.0.1
2017-08-29T19:48:43.422+0200 insertDocument :: caused by :: 11000 E11000 duplicate key error index: vote-db.votemodels.$_id_  dup key: { : ObjectId('561a665a0553b9fe3870dfca') }
2017-08-29T19:48:43.422+0200 insertDocument :: caused by :: 11000 E11000 duplicate key error index: vote-db.votemodels.$_id_  dup key: { : ObjectId('561a665a0553b9fe3870dfcb') }
exception:BSON representation of supplied JSON is too large: code FailedToParse: FailedToParse: Field name expected: offset:1 of:{
exception:BSON representation of supplied JSON is too large: code FailedToParse: FailedToParse: Expecting '{': offset:0 of:  "__v": 0,
exception:BSON representation of supplied JSON is too large: code FailedToParse: FailedToParse: Expecting '{': offset:0 of:  "_id": {
exception:BSON representation of supplied JSON is too large: code FailedToParse: FailedToParse: Expecting '{': offset:0 of:    "$oid": "561a665a0553b9fe3870dfcc"
exception:BSON representation of supplied JSON is too large: code FailedToParse: FailedToParse: Expecting '{': offset:0 of:  },
exception:BSON representation of supplied JSON is too large: code FailedToParse: FailedToParse: Expecting '{': offset:0 of:  "choices": [
exception:BSON representation of supplied JSON is too large: code FailedToParse: FailedToParse: Field name expected: offset:5 of:    {
exception:BSON representation of supplied JSON is too large: code FailedToParse: FailedToParse: Expecting '{': offset:0 of:      "count": 1700,
exception:BSON representation of supplied JSON is too large: code FailedToParse: FailedToParse: Expecting '{': offset:0 of:      "id": "choice_1",
exception:BSON representation of supplied JSON is too large: code FailedToParse: FailedToParse: Expecting '{': offset:0 of:      "title": "Depeche Mode"
exception:BSON representation of supplied JSON is too large: code FailedToParse: FailedToParse: Expecting '{': offset:0 of:    },
exception:BSON representation of supplied JSON is too large: code FailedToParse: FailedToParse: Field name expected: offset:5 of:    {
exception:BSON representation of supplied JSON is too large: code FailedToParse: FailedToParse: Expecting '{': offset:0 of:      "count": 2212,
exception:BSON representation of supplied JSON is too large: code FailedToParse: FailedToParse: Expecting '{': offset:0 of:      "id": "choice_2",
exception:BSON representation of supplied JSON is too large: code FailedToParse: FailedToParse: Expecting '{': offset:0 of:      "title": "Metallica"
exception:BSON representation of supplied JSON is too large: code FailedToParse: FailedToParse: Expecting '{': offset:0 of:    },
exception:BSON representation of supplied JSON is too large: code FailedToParse: FailedToParse: Field name expected: offset:5 of:    {
exception:BSON representation of supplied JSON is too large: code FailedToParse: FailedToParse: Expecting '{': offset:0 of:      "count": 267,
exception:BSON representation of supplied JSON is too large: code FailedToParse: FailedToParse: Expecting '{': offset:0 of:      "id": "choice_3",
exception:BSON representation of supplied JSON is too large: code FailedToParse: FailedToParse: Expecting '{': offset:0 of:      "title": "Napalm Death"
exception:BSON representation of supplied JSON is too large: code FailedToParse: FailedToParse: Expecting '{': offset:0 of:    },
exception:BSON representation of supplied JSON is too large: code FailedToParse: FailedToParse: Field name expected: offset:5 of:    {
exception:BSON representation of supplied JSON is too large: code FailedToParse: FailedToParse: Expecting '{': offset:0 of:      "count": 1231,
exception:BSON representation of supplied JSON is too large: code FailedToParse: FailedToParse: Expecting '{': offset:0 of:      "id": "choice_4",
exception:BSON representation of supplied JSON is too large: code FailedToParse: FailedToParse: Expecting '{': offset:0 of:      "title": "Iron Maiden"
exception:BSON representation of supplied JSON is too large: code FailedToParse: FailedToParse: Expecting '{': offset:0 of:    },
exception:BSON representation of supplied JSON is too large: code FailedToParse: FailedToParse: Field name expected: offset:5 of:    {
exception:BSON representation of supplied JSON is too large: code FailedToParse: FailedToParse: Expecting '{': offset:0 of:      "count": 800,
exception:BSON representation of supplied JSON is too large: code FailedToParse: FailedToParse: Expecting '{': offset:0 of:      "id": "choice_5",
exception:BSON representation of supplied JSON is too large: code FailedToParse: FailedToParse: Expecting '{': offset:0 of:      "title": "Motörhead"
exception:BSON representation of supplied JSON is too large: code FailedToParse: FailedToParse: Expecting '{': offset:0 of:    },
exception:BSON representation of supplied JSON is too large: code FailedToParse: FailedToParse: Field name expected: offset:5 of:    {
exception:BSON representation of supplied JSON is too large: code FailedToParse: FailedToParse: Expecting '{': offset:0 of:      "count": 1122,
exception:BSON representation of supplied JSON is too large: code FailedToParse: FailedToParse: Expecting '{': offset:0 of:      "id": "choice_6",
exception:BSON representation of supplied JSON is too large: code FailedToParse: FailedToParse: Expecting '{': offset:0 of:      "title": "The Fall"
exception:BSON representation of supplied JSON is too large: code FailedToParse: FailedToParse: Expecting '{': offset:0 of:    }
exception:BSON representation of supplied JSON is too large: code FailedToParse: FailedToParse: Expecting '{': offset:0 of:  ],
exception:BSON representation of supplied JSON is too large: code FailedToParse: FailedToParse: Expecting '{': offset:0 of:  "description": "What music are you listening to?",
exception:BSON representation of supplied JSON is too large: code FailedToParse: FailedToParse: Expecting '{': offset:0 of:  "id": "vote_3",
exception:BSON representation of supplied JSON is too large: code FailedToParse: FailedToParse: Expecting '{': offset:0 of:  "title": "Favorite band",
exception:BSON representation of supplied JSON is too large: code FailedToParse: FailedToParse: Expecting '{': offset:0 of:  "user": "Marry"
exception:BSON representation of supplied JSON is too large: code FailedToParse: FailedToParse: Expecting '{': offset:0 of:}
2017-08-29T19:48:43.424+0200 imported 2 objects

content of npm-debug.log is:

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'run',
1 verbose cli   'import-mongodb-data' ]
2 info using npm@3.10.10
3 info using node@v6.11.2
4 verbose run-script [ 'preimport-mongodb-data',
4 verbose run-script   'import-mongodb-data',
4 verbose run-script   'postimport-mongodb-data' ]
5 info lifecycle react-vote-example@1.0.0~preimport-mongodb-data: react-vote-example@1.0.0
6 silly lifecycle react-vote-example@1.0.0~preimport-mongodb-data: no script for preimport-mongodb-data, continuing
7 info lifecycle react-vote-example@1.0.0~import-mongodb-data: react-vote-example@1.0.0
8 verbose lifecycle react-vote-example@1.0.0~import-mongodb-data: unsafe-perm in lifecycle true
9 verbose lifecycle react-vote-example@1.0.0~import-mongodb-data: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/home/jannik/react/vote-example-master/app/node_modules/.bin:/home/jannik/bin:/home/jannik/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
10 verbose lifecycle react-vote-example@1.0.0~import-mongodb-data: CWD: /home/jannik/react/vote-example-master/app
11 silly lifecycle react-vote-example@1.0.0~import-mongodb-data: Args: [ '-c',
11 silly lifecycle   'mongoimport --db vote-db --collection votemodels ./src/server/db/mongodb-votes.json' ]
12 silly lifecycle react-vote-example@1.0.0~import-mongodb-data: Returned: code: 255  signal: null
13 info lifecycle react-vote-example@1.0.0~import-mongodb-data: Failed to exec import-mongodb-data script
14 verbose stack Error: react-vote-example@1.0.0 import-mongodb-data: `mongoimport --db vote-db --collection votemodels ./src/server/db/mongodb-votes.json`
14 verbose stack Exit status 255
14 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:891:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid react-vote-example@1.0.0
16 verbose cwd /home/jannik/react/vote-example-master/app
17 error Linux 4.4.0-93-generic
18 error argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "import-mongodb-data"
19 error node v6.11.2
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error react-vote-example@1.0.0 import-mongodb-data: `mongoimport --db vote-db --collection votemodels ./src/server/db/mongodb-votes.json`
22 error Exit status 255
23 error Failed at the react-vote-example@1.0.0 import-mongodb-data script 'mongoimport --db vote-db --collection votemodels ./src/server/db/mongodb-votes.json'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the react-vote-example package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     mongoimport --db vote-db --collection votemodels ./src/server/db/mongodb-votes.json
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs react-vote-example
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls react-vote-example
3 error Or if that isn't available, you can get their info via:
23 error     npm owner ls react-vote-example
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

What I'm doing wrong?

**Comment by jannik8x8** [comment]
I surrounded the three blocks with squared brackets and delimited the {} blocks with a coma. 
So it looked like
[
 { ...},
 { ...},
 { ...}
]
and I imported it with 
mongoimport --db vote-db --collection votemodels --jsonArray ./src/server/db/mongodb-votes.json

This seemed to work.

**Comment by nilshartmann** [comment]
Hi,

i've tested it with Mongo v3.4.7 and it works for me. Maybe the file format of the json-file for mongoimport has changed between 2.6 and 3.4?
